### ISSUE TITLE
Thanks, paper, roadmap and remark

### ISSUE THREAD

**Issue by mdelozzo** [efekhari27/copulogram#1]
Hello,

This chart is very interesting and could be helpful to get a better idea of dependencies. Thanks for this dataviz contribution.

Do you have a paper associated with this Python project?

Regarding you roadmap, do you plan to link `Copulogram` and `NonParametricModel`?

Lastly, I find it confusing to read ranks in the physical scale. Why not add axes at the top and on the right, with $[0,1]$ or $[0,100]$ intervals?

Regards

**Comment by efekhari27** [comment]
Hello Matthias, 

Thank you for this nice feedback. We are currently working on a preprint regarding this plot. 

I was initially working on fitting multivariate distributions on samples presenting a strong dependence structure. Then @vchabri  and I looked into nonparametric copula fitting methods such as the [Empirical Bernstein Copula implemented in OpenTURNS](http://openturns.github.io/openturns/latest/user_manual/_generated/openturns.EmpiricalBernsteinCopula.html#openturns.EmpiricalBernsteinCopula). This method applies a multivariate Bernstein approximation on the empirical copula. 

The generic goal of the `Copulogram` is to visually decompose each elements of a multivariate dataset (its marginals and its empirical copula). If the user needs to fit a model on a multivariate dataset, the `NonParametricModel` provides him a fully nonpararametric way to do so (based on OpenTURNS methods). Then, the user can generate a sample from this model and visually compare its Copulogram to the initial one. 

About the shared axis, I agree that this would improve the plot. The seaborn class currently used (`sns.PairGrid`), forces all the rows and columns to share the same axis. For more flexibility, I am considering to move towards another class  such as `sns.FacedGrid` or directly work with matplotlib subplots. 

If you have more suggestions or ideas, I will be glad to discuss them. 
Regards, 
Elias

**Comment by mdelozzo** [comment]
Thanks for your answer. In that case, I'll wait for the preprint and continue to follow your activity.

In the context of my work, I'm looking into copulas and their implementations in OpenTURNS. I'm sure that your `NonParametricModel` and `Copulogram` will inspire me. I will try to use them in the next weeks/months.

About the shared axis, from my experience, matplotlib is harder to handle, but in the end you can do much more. I implemented a [customizable scatter matrix](https://gitlab.com/gemseo/dev/gemseo/-/blob/develop/src/gemseo/post/dataset/scatter_plot_matrix.py?ref_type=heads) and I discovered that you can finely tune the different subplots. More precisely, I started from the scatter matrix proposed by pandas and then changed some properties with matplolib. Perhaps you could do the same kind of things as seaborn relies also on matplotlib (`sns.PairGrid.figure` allows to play with the matplotlib figure).

**Comment by efekhari27** [comment]
I was looking at a way to hack the PairGrid axes by removing the shared-axis constraint but I think that it will take less effort to start over in pure matplotlib with something similar as what you did. 
Thanks for sharing your experience. 
Elias

**Comment by mdelozzo** [comment]
You're welcome :)

That's it for me. I'm closing this ticket.
